version: '2'
services:
    jenkins:
        image: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - '/var/jenkins_home:/var/jenkins_home'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/usr/bin/docker:/usr/bin/docker'
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab.localhost.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://gitlab.localhost.com:9080'
              gitlab_rails['gitlab_shell_ssh_port'] = 2234
        ports:
            - '9080:9080'
            - '2234:22'
        volumes:
            - '/srv1/gitlab/config:/etc/gitlab'
            - '/srv1/gitlab/logs:/var/log/gitlab'
            - '/srv1/gitlab/data:/var/opt/gitlab'
    registry-srv:
        restart: always
        image: registry:2
        ports:
            - 5000:5000
        volumes:
            - /var/registry:/var/lib/registry
    registry-web:
        restart: always
        image: hyper/docker-registry-web 
        ports:
            - 8080:8080
        environment:
            - REGISTRY_URL=http://registry-srv:5000/v2
            - REGISTRY_NAME=localhost:5000
        links:
            - registry-srv
        volumes:
            - /var/registry-web/data:/data
            - /var/registry-web/app:/usr/local/app

    
    
